"""add cascade for projects table

Revision ID: 44fda1777a07
Revises: 4a8796af82d2
Create Date: 2023-07-30 05:22:01.020478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44fda1777a07'
down_revision = '4a8796af82d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'projects', ['id'])
    op.create_unique_constraint(None, 'tasks', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'tasks', type_='unique')
    op.drop_constraint(None, 'projects', type_='unique')
    # ### end Alembic commands ###
