"""update role

Revision ID: 6d44d235fc50
Revises: f3be9afd3569
Create Date: 2023-08-01 17:35:35.069617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d44d235fc50'
down_revision = 'f3be9afd3569'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
