"""change role value

Revision ID: 78172ce90787
Revises: e8d1924727df
Create Date: 2023-07-31 18:02:28.951346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78172ce90787'
down_revision = 'e8d1924727df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
