"""add unique constraint for user_project table

Revision ID: d8b299f38e10
Revises: ea9d2a95d127
Create Date: 2023-07-30 06:44:53.331780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8b299f38e10'
down_revision = 'ea9d2a95d127'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_project_uc1', 'user_project', ['user_id', 'project_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_project_uc1', 'user_project', type_='unique')
    # ### end Alembic commands ###
