"""add cascade for projects table

Revision ID: d91173e73cf7
Revises: 44fda1777a07
Create Date: 2023-07-30 05:25:31.976329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd91173e73cf7'
down_revision = '44fda1777a07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_project_project_id_fkey', 'user_project', type_='foreignkey')
    op.create_foreign_key(None, 'user_project', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_project', type_='foreignkey')
    op.create_foreign_key('user_project_project_id_fkey', 'user_project', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###
