"""remove unique for task title

Revision ID: e8d1924727df
Revises: fb6b4f43f4d1
Create Date: 2023-07-30 10:28:52.641676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8d1924727df'
down_revision = 'fb6b4f43f4d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_title', table_name='tasks')
    op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_title'), table_name='tasks')
    op.create_index('ix_tasks_title', 'tasks', ['title'], unique=False)
    # ### end Alembic commands ###
