"""remove cascade from projects table

Revision ID: fb6b4f43f4d1
Revises: d8b299f38e10
Create Date: 2023-07-30 08:04:58.702377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb6b4f43f4d1'
down_revision = 'd8b299f38e10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
